# Generated by Django 5.0.7 on 2026-06-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KGS', max_length=8)),
                ('color', models.CharField(default='#111827', max_length=24)),
                ('icon', models.CharField(default='wallet', max_length=48)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=12)),
                ('color', models.CharField(default='#2563eb', max_length=24)),
                ('icon', models.CharField(default='tag', max_length=48)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('owed_by_me', 'Я должен'), ('owed_to_me', 'Мне должны')], max_length=20)),
                ('person', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('paid', 'Закрыт'), ('overdue', 'Просрочен')], default='open', max_length=16)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['status', 'due_date', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('color', models.CharField(default='#16a34a', max_length=24)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод'), ('return', 'Возврат'), ('saving', 'Накопление')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('transfer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='finance.account')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
            ],
            options={
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
